version: '3.3'
services:

argoverse_environement:
  build:
    context: .
    dockerfile: Dockerfile
  tty: true
  environment:
    - DISPLAY=${DISPLAY}
  container_name: argoverse
  ports:
    - "8888:8888"
  volumes:
    - type: bind
      source: "./"
      target: "/work"
    - type: bind
      source: "/tmp/.X11-unix"
      target: "/tmp/.X11-unix"
  command: /bin/bash
  deploy:
    resources:
      reservations:
        devices:
        - driver: nvidia
          capabilities: [utility, compute, video]
