version: '3.3'
services:

  ros-pytorch_environment:
    build:
      context: .
      dockerfile: Dockerfile
    tty: true
    environment:
      - DISPLAY=${DISPLAY}
    container_name: dense_tnt
    ports:
      - "8888:8888"
    volumes:
      - type: bind
        source: "./"
        target: "/work"
      - type: bind
        source: "/tmp/.X11-unix"
        target: "/tmp/.X11-unix"
    command: /bin/bash
    deploy:
      resources:
        reservations:
          devices:
          - driver: nvidia
            capabilities: [utility, compute, video]
